### ISSUE TITLE
why comments is null

### ISSUE THREAD

**Issue by MarsCaiWORD** [InstaSharp/InstaSharp#100]
![image](https://cloud.githubusercontent.com/assets/14837356/13608879/9fe1624a-e591-11e5-8b36-dd1ba0cb6007.png)

**Comment by momenimohammad23** [comment]
Becuse you are in sandbox mode

**Comment by MarsCaiWORD** [comment]
So what I need to do

**Comment by MariuszPL55** [comment]
I see that author of this project is sleeping

**Comment by fujiy** [comment]
@MariuszPL55 it's a community, everybody can help including you

**Comment by fujiy** [comment]
https://www.instagram.com/developer/sandbox/
