### ISSUE TITLE
Relationship Actions Failing... returning null

### ISSUE THREAD

**Issue by AnthonyMascia** [InstaSharp/InstaSharp#102]
```
var unfollow = await relationships.Relationship(id, InstaSharp.Endpoints.Relationships.Action.Unfollow);

                     if (unfollow.Data.OutgoingStatus == OutgoingStatus.None)
                        throw new ArgumentException("Failed");
```

unfollow.Data is returning null. Do the actions need to be updated?

**Comment by fujiy** [comment]
Please post the Meta property  content

**Comment by momenimohammad23** [comment]
its becuse you are in sandbox mode , 
just can see the users who in your sandbox user
for example you get relation of a user with id : 11111 and the this user follow anothe user with id : 22222
if both of 11111 , 22222 are in your sandbox user you can see them if not , you cant see them

**Comment by fujiy** [comment]
Thanks @momenimohammad23
