### ISSUE TITLE
Platform Policy

### ISSUE THREAD

**Issue by di48l069** [InstaSharp/InstaSharp#103]
Don't use the Instagram API to simply display User Content, import or backup content, or manage Instagram relationships, without our prior permission.

does this mean the majority of this library functionality is pointless?

**Comment by momenimohammad23** [comment]
nobody can use instagram api ... :(

**Comment by di48l069** [comment]
Ya i'm not sure

https://www.instagram.com/about/legal/terms/api/

I hate the fact we cant even use "Insta", "Instagram" and "Gram" in our application

**Comment by Telaran** [comment]
> > Don't use the Instagram API to simply display User Content, import or backup content, or manage Instagram relationships, without our prior permission.

> does this mean the majority of this library functionality is pointless?

Policy, Licensing, etc are always a bit complicated and many of them is not even clear if you have a lawyer as friend to check them.

_**About your question:**_
The whole statement is more likely against reverse engineered interfaces and their right to go against them. The important part of the statement is **without our prior permission**. InstaSharp require an API-Key which you can only get if you have an Instagram Account and also an App registered. For the full usage you also have to go through a full review process (were you have to show your app).

So it's not easy to say if and what they will approve from your app or not. In one of the project I was involved we required three retries before we got approved for all permissions we wanted to implement in the application. 

It's not easy and it doesn't matter which Social-Platform you have to connect.
