### ISSUE TITLE
Can not get feed, returns 404 not found.

### ISSUE THREAD

**Issue by karincalab** [InstaSharp/InstaSharp#104]
I tried the test MVC app and authenticated successfully, but could not get the user feed. It always returns 

Response status code does not indicate success: 404 (NOT FOUND).

Could you please help on this?

**Comment by fujiy** [comment]
The Instagram API is changing. New clients doesn't support some endpoints:https://www.instagram.com/developer/changelog/

> Deprecation of /users/self/feed
