### ISSUE TITLE
Can this wrapper be used in a windows app?

### ISSUE THREAD

**Issue by robertJurado** [InstaSharp/InstaSharp#110]
Is it possible to use this wrapper as a windows application instead?

Thanks in advance.

Robert J>

**Comment by assassin316** [comment]
@fujiy 

I was wondering the same thing. It's based in C#, so I'm sure this is possible. I'd like to use it in a UWP project. Is there a sample somewhere ??

**Comment by fujiy** [comment]
I've never used, but I guess it works.

After Instagram changed some policies I can't test the API anymore. So can't guarantee it will work in any platform.
