### ISSUE TITLE
Tag Subscription

### ISSUE THREAD

**Issue by aerionTech** [InstaSharp/InstaSharp#113]
Do any of the subscriptions beside User's work? 
When attempting to create a Tag Subscription i get the following error
Response status code does not indicate success: 404 (Not Found).

```
SubscriptionResponse createTagSub = await subscription.CreateTag("MYTAG", "MYTAG_TOKEN");
```

**Comment by fujiy** [comment]
It was removed: "Deprecation of Realtime subscriptions for tags, locations and geographies"
https://www.instagram.com/developer/changelog/

**Comment by aerionTech** [comment]
Thanks for the update.
