### ISSUE TITLE
Why does RequestToken return Null all the time ??  

### ISSUE THREAD

**Issue by assassin316** [InstaSharp/InstaSharp#120]
Anyone else experience this ??  I saw another post about adding the Content Type, but how is that done?

**Comment by Adalyat** [comment]
Not sure that my answer will be useful for you, but I had the same problem. In my own project RequestToken returns OAuthResponse with null-value properties. I cloned this repo and run it locally, and found that RequestToken works fine! I'm really confused. After that I recreate RequestToken locally and used it directly (with the same config) instead of auth.RequestToken and now I got success!

**Comment by assassin316** [comment]
Apparently there is something about the IP being blocked from Instagram when making too many invalid calls, I'll need to try it:

#115

**Comment by assassin316** [comment]
So in the end, I tried it on another device to obtain a different IP, and same result, RequestToken returns OAuthResponse with null-value properties. 

I don't know MVC, i'm using this library in a UWP project.

**Comment by Adalyat** [comment]
Did you tried to implement your own RequestToken method in your project (copy from this repo) ? I have no ideas why it works, but it does.

**Comment by assassin316** [comment]
What I'm noticing is the problems begin before I even get to the RequestToken, it's during the Authentication flow. So I did just that with a few other changes. I start the login process with the WebAuthenticationBroker as such:

		var scopes = new List<OAuth.Scope>();
		scopes.Add(InstaSharp.OAuth.Scope.Basic);

		var link = InstaSharp.OAuth
						.AuthLink
						(
							_config.OAuthUri + "authorize",
							_config.ClientId,
							_config.RedirectUri,
							scopes,
							InstaSharp.OAuth.ResponseType.Token
						);

		var webAuthResult = await WebAuthenticationBroker
										.AuthenticateAsync
										(
											WebAuthenticationOptions.None,
											new Uri(link)
										);
													
		switch (webAuthResult.ResponseStatus)
		{
			case WebAuthenticationStatus.Success:
				return true;

			case WebAuthenticationStatus.UserCancel:
				return false;

			case WebAuthenticationStatus.ErrorHttp:
				return false;

			default:
				return false;
		}

So all begins well, the user gets a popup which asks for their login. Once I enter the credentials and Login, I receive is a Http 400. Here is a screenshot of the error when clicking the login in the popup:

![image](https://cloud.githubusercontent.com/assets/17514380/19485236/71e598b0-9528-11e6-9be2-1a00f4bf43f0.png)

**Comment by fujiy** [comment]
ARe you using version 2.0.4?

**Comment by assassin316** [comment]
@fujiy  Thanks Felipe!

I'm going to try it as soon as I can, unfortunately I can't upgrade to 2.0.5 since I'm using InstaSharp in a PCL project and the cryptography dependency is not PCL-ready.

I'll look for a workaround to the issue.

**Comment by assassin316** [comment]
Ok, that explains it  :)  thanks for the quick reply.

And just for information purposes, this was the error. If I do find a workaround, I'll post it here  :)

"Could not install package 'System.Security.Cryptography.Algorithms 4.3.0'. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework."

**Comment by fujiy** [comment]
Unfortunately  Windows 8.1 doesn't support Net Standard 1.3: https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

**Comment by fujiy** [comment]
I think I'll need to go back to Bouncy Castle

**Comment by fujiy** [comment]
Done

**Comment by assassin316** [comment]
@fujiy  2.0.6 working perfectly!!   Thanks!!  :)
