### ISSUE TITLE
Sign Out of InstaSharp

### ISSUE THREAD

**Issue by ssepac** [InstaSharp/InstaSharp#125]
Hi, 

I am trying to make it so that I can sign out the current logged in user who authenticated with Instagram so that others can return to the homepage to sign in using their account. I'm not sure how to do this... I tried making
`Session["InstaSharp.Info] = null;`

but when I click my login button it just resigns in the former user without prompting a new one to log in. Does anyone know how I can make the user redirected to the Instagram login form?

**Comment by fujiy** [comment]
Thats because the user is logged in on Instagram, so he needs to sign out there
