### ISSUE TITLE
Doesn't compile on a UWP project

### ISSUE THREAD

**Issue by assassin316** [InstaSharp/InstaSharp#128]
Hi @fujiy,

I'm getting a problem. Adding Instasharp to a UWP project (even just an empty project) gives the following errors:

	 error APPX1101: Payload contains two or more files with the same destination path 'Microsoft.Win32.Primitives.dll'. Source files: 
	 error APPX1101: ...\.nuget\packages\Microsoft.Win32.Primitives\4.0.0\lib\dotnet\Microsoft.Win32.Primitives.dll
	 error APPX1101: ...\.nuget\packages\runtime.win.Microsoft.Win32.Primitives\4.0.1\runtimes\win\lib\netstandard1.3\Microsoft.Win32.Primitives.dll
	 error APPX1101: Payload contains two or more files with the same destination path 'System.Diagnostics.Tools.dll'. Source files: 
	 error APPX1101: ...\.nuget\packages\runtime.any.System.Diagnostics.Tools\4.0.1\lib\netcore50\System.Diagnostics.Tools.dll
	 error APPX1101: ...\.nuget\packages\System.Diagnostics.Tools\4.0.0\lib\netcore50\System.Diagnostics.Tools.dll
	 error APPX1101: Payload contains two or more files with the same destination path 'System.Globalization.Calendars.dll'. Source files: 
	 error APPX1101: ...\.nuget\packages\runtime.any.System.Globalization.Calendars\4.0.1\lib\netcore50\System.Globalization.Calendars.dll
	 error APPX1101: ...\.nuget\packages\System.Globalization.Calendars\4.0.0\lib\netcore50\System.Globalization.Calendars.dll
	 error APPX1101: Payload contains two or more files with the same destination path 'System.Threading.Timer.dll'. Source files: 
	 error APPX1101: ...\.nuget\packages\runtime.any.System.Threading.Timer\4.0.1\lib\netcore50\System.Threading.Timer.dll
	 error APPX1101: ...\.nuget\packages\System.Threading.Timer\4.0.0\lib\netcore50\System.Threading.Timer.dll
	 error APPX1101: Payload contains two or more files with the same destination path 'System.Net.Sockets.dll'. Source files: 
	 error APPX1101: ...\.nuget\packages\runtime.win.System.Net.Sockets\4.1.0\runtimes\win\lib\netcore50\System.Net.Sockets.dll
	 error APPX1101: ...\.nuget\packages\System.Net.Sockets\4.0.0\lib\netcore50\System.Net.Sockets.dll

**Comment by assassin316** [comment]
@fujiy  Any idea on this bug and why it's happening?  I can't continue with this library on UWP due to this error.

**Comment by fujiy** [comment]
Are you referencing the NuGet package or the InstaSharp source code? Please try again with the latest source

**Comment by assassin316** [comment]
@fujiy 

I'm referencing the 2.0.6 nuget package in a UWP library.

I have a link to a sample project demonstrating the issue:

[http://stackoverflow.com/questions/42794676/payload-contains-two-or-more-files](http://stackoverflow.com/questions/42794676/payload-contains-two-or-more-files)

**Comment by assassin316** [comment]
@fujiy  I also tried to downgrade to 2.0.5 hoping maybe it was a change in the latest version, but still got the same error.   :\

**Comment by fujiy** [comment]
@assassin316 I can compile your project after updating the Microsoft.NETCore.UniversalWindowsPlatform package.
The problem is not related to Instasharp itself

**Comment by assassin316** [comment]
Thank you!!  Didn't even notice that.
