### ISSUE TITLE
.NET Framework Target

### ISSUE THREAD

**Issue by francnuec** [InstaSharp/InstaSharp#129]
So I tried updating my packages yesterday but nuget won't install InstaSharp, because my project targets .net 4.5.

Here's the full error:

> Could not install package 'InstaSharp 2.0.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Please help.

**Comment by FarazTalpur** [comment]
Try with v4.6. It worked for me

**Comment by fujiy** [comment]
You need 4.5.1 at least
