### ISSUE TITLE
Incorrect formatted Hashtag throws JsonReaderException

### ISSUE THREAD

**Issue by minimih** [InstaSharp/InstaSharp#37]
If a Hashtag is incorrect formatted (eg. "csharp.asp" or "csharp asp") then a JsonReaderException is thrown. The error is thrown because Json.net can't deserialize the result in a MediaResponse Object.

If i test the two Hashtags above in the Instagram API it returns a 404 Error.

Examples:
* correct hashtag: https://api.instagram.com/v1/tags/csharpasp/media/recent?access_token=1415228826.554dfe9.502432355f084ea581b679a2f94bb350
* incorrect hashtag: https://api.instagram.com/v1/tags/csharp.asp/media/recent?access_token=1415228826.554dfe9.502432355f084ea581b679a2f94bb350

I think InstaSharp should return a 404 Error in the meta information or return a empty MediaResponse Object.

**Comment by fujiy** [comment]
Fixed by @damiangreen
