### ISSUE TITLE
Loading next page of images with Instasharp

### ISSUE THREAD

**Issue by mdmoura** [InstaSharp/InstaSharp#42]
Hello,

I am using Instasharp and I need to get paginated sets of images tagged with "Car":

  String clientId = "xyz";
  String clientSecret = "xyz";
  var config = new InstagramConfig(clientId, clientSecret);
  var query = new InstaSharp.Endpoints.Tags(config);
  var reply1 = query.Recent("pet", null, null, 2);
  var reply2 = query.RecentMultiplePages("pet", null, null, 20, null);

When I check reply2 I see that 600 items were loaded and PageCount is equal to 20.

And I also get a PaginationNextMaxId ..

The point is that I do want to load all items.

I need to load only 20 and to have enough information to load the next 20.

Does anyone knows how can I do this?

Thank You,
Miguel

**Comment by damiangreen** [comment]
Your questions is a little confusing, you say you do want to load all items, then you say you want to load only 20?

**Comment by mdmoura** [comment]
Sorry, maybe I explained myself wrong. 

I need to load the first 20, then the next 20, then the next 20, ...

I tried the following:

      public MediaWrap GetImages(String tag, String nextMaxId) {

          String clientId = "xyz";
          String clientSecret = "xyz";
          var config = new InstagramConfig(clientId, clientSecret);
          var query = new InstaSharp.Endpoints.Tags(config);

          var reply = await query.Recent(tag, null, nextMaxId, 32);

          return new MediaWrap {
              InstagramNextMaxId = reply.Pagination.NextMaxId,
              Medias = reply.Data
          } 
      }

The first time I call GetImages nextMaxId is null so I load the most recent 32.

The secont time, and forward, I call GetImages I pass the NexMaxId of the previous call.

So I get the next 32. Does this make sense?

Or is there another way to do paging?

**Comment by damiangreen** [comment]
You could either grab 2 page; use 
       var result = await query.RecentMultiplePages(tag, null, null, 2); 
This would return around 66 results
Then you could just chain with .Take(60); If you're after just 60 results. 
The 33 items that are being returned per page is not documented anywhere in Instagram

**Comment by mdmoura** [comment]
Does it always return 33 records per page?

When you use 

     query.RecentMultiplePages(tag, null, null, 2); 
 
You are taking 2 pages ... But which pages? 1 and 2? 3 and 4?

You are not using an index ... How do you Know you will not get the same images?

**Comment by damiangreen** [comment]
It seems to alwys return 33, but that may change in the future, hence why i mentioned its not documented. It will take the most recent x pages, i.e. the most recent 33 +33 pages
