### ISSUE TITLE
How to check login user name and password as a bulk

### ISSUE THREAD

**Issue by beljk** [InstaSharp/InstaSharp#45]
i don't know hot to use this api .. so can give me an example .. i get clientID and Client Secret ..

**Comment by damiangreen** [comment]
your question doesn't make a whole lot of sense. Have you looked at the documentation + tests?

**Comment by beljk** [comment]
@damiangreen ,Yes .. but i don't know from where i will start . so can you give me example

**Comment by momenimohammad23** [comment]
did you find a good example ?
I found MVC example but it doesent work !!
