### ISSUE TITLE
Instagram Followers Count

### ISSUE THREAD

**Issue by JMStacy86** [InstaSharp/InstaSharp#47]
Is there a way to pull down the number of followers or who they are following on an instagram account without having to receive an access token to retrieve this information. I don't need the usernames of any of the friends or anything personal of that nature.  I just need the quantitative number for analytics/reach purposes.  I am running an application that in needing an authentication from the user would ruin the overall user flow/create longer lines.  Thanks in advance for your time.

**Comment by fujiy** [comment]
You can use the InstaSharp.Endpoints.Users.Get method, passing the userId as argument
