### ISSUE TITLE
Basic MVC 5 Website Using Instasharp

### ISSUE THREAD

**Issue by adrobson** [InstaSharp/InstaSharp#48]
Hi Guys

Sorry about being slow but I'm just trying to connect a site using the MVC web project template in Visual Studio. Could somebody give me some quick pointers or it might actually be easier to update the solution so it has an MVC project to connect with?

I'll take you through what I've done and where I've got stuck

1) unzipped Instasharp solution
2) Added web project using MVC and added reference to Instasharp 
3) Update web.config with the appropriate settings for my Instagram App (client id etc)
4) Replaced About.cshtml with the following:

    @using InstaSharp
    @using System.Configuration

@{
    ViewBag.Title = "About";
}

    <div class="row">
    @{
        var clientId = ConfigurationManager.AppSettings["vts_instagram_client_Id"];
        var clientSecret = ConfigurationManager.AppSettings["vts_instagram_client_secret"];
        var redirectUri = ConfigurationManager.AppSettings["vts_instagram_redirect_uri"];
        var realtimeUri = "";

        InstagramConfig config = new InstagramConfig(clientId, clientSecret, redirectUri, realtimeUri);
        // create the auth url
        var scopes = new List<OAuth.Scope>();
        scopes.Add(OAuth.Scope.Likes);
        scopes.Add(OAuth.Scope.Comments);

        var link = OAuth.AuthLink(config.OAuthUri + "/authorize", config.ClientId, config.RedirectUri, scopes, OAuth.ResponseType.Code);
    }
</div>

 5) Replaced Index method of the HomeController with the following:
        [GET("oauth")]
        public async Task<ActionResult> Index(string code)
        {
            // add this code to the auth object
            var auth = new InstaSharp.OAuth(config);

            // now we have to call back to instagram and include the code they gave us
            // along with our client secret
            var oauthResponse = await auth.RequestToken(code);

            // tell the session that we are authenticated
            config.isAuthenticated = true;

            // both the client secret and the token are considered sensitive data, so we won't be
            // sending them back to the browser. we'll only store them temporarily.  If a user's session times
            // out, they will have to click on the authenticate button again - sorry bout yer luck.
            Session.Add("InstaSharp.AuthInfo", oauthResponse);

            // all done, lets redirect to the home controller which will send some intial data to the app
            return RedirectToAction("Index", "Home");
        }

The first problem is GET("oauth") is not recognised by the compiler. Should it be HTTPGet? If so there doesn't seem to be an option to use a parameter ("oauth") with it?

Second problem is config is not recognised. Should I have created a new instance of InstagramConfig ? If so, there isn't an isAuthenticated property of InstagramConfig.

**Comment by momenimohammad23** [comment]
did you solve it ?
:(
i cant work with instasharp in MVC
can you help me or get me a sample ?

**Comment by adrobson** [comment]
I dont think I ever did
Sorry I cant help

Date: Mon, 14 Sep 2015 02:46:04 -0700

**Comment by momenimohammad23** [comment]
Can you send to me you basic sample , just i want to connect and get my profile info !

**Comment by fujiy** [comment]
https://github.com/InstaSharp/InstaSharp/commit/60ef02f7ff832f84620b53684b8e8d3de85a29ef

**Comment by michelank** [comment]
Hi guys,

Take a look at my controller:

namespace Instagram.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Login()
        {
            var scopes = new List<OAuth.Scope>();
            scopes.Add(OAuth.Scope.Likes);
            scopes.Add(OAuth.Scope.Comments);

            var link = OAuth.AuthLink(InstaConfig.Instance.OAuthUri + "authorize",
                InstaConfig.Instance.ClientId,
                InstaConfig.Instance.RedirectUri,
                scopes,
                OAuth.ResponseType.Code);

            return Redirect(link);
        }

        [Route("callback")]
        [HttpGet]
        public async Task<ActionResult> Callback(string code)
        {
            // add this code to the auth object
            var auth = new OAuth(InstaConfig.Instance);

            // now we have to call back to instagram and include the code they gave us
            // along with our client secret
            var oauthResponse = await auth.RequestToken(code);

            // both the client secret and the token are considered sensitive data, so we won't be
            // sending them back to the browser. we'll only store them temporarily.  If a user's session times
            // out, they will have to click on the authenticate button again - sorry bout yer luck.
            Session.Add("InstaSharp.AuthInfo", oauthResponse);

            // all done, lets redirect to the home controller which will send some intial data to the app
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> MyFeed()
        {
            var oAuthResponse = Session["InstaSharp.AuthInfo"] as OAuthResponse;

            if (oAuthResponse == null)
            {
                return RedirectToAction("Login");
            }

            var users = new InstaSharp.Endpoints.Users(InstaConfig.Instance, oAuthResponse);

            var feed = await users.Feed(null, null, null);

            return View(feed.Data);
        }
    }
}`

**Comment by michelank** [comment]
Hi guys,

Take a look:

```
public ActionResult Login()
{}

[Route("callback")]
[HttpGet]
public async Task<ActionResult> Callback(string code)
{}

public async Task<ActionResult> MyFeed()
{}
```
