### ISSUE TITLE
What is the status of the Realtime API

### ISSUE THREAD

**Issue by bradserbu** [InstaSharp/InstaSharp#50]

**Comment by damiangreen** [comment]
it's all there. Are you having an issue?

**Comment by bradserbu** [comment]
Is it only there for managing the subscriptions to the realtime Endpoints?  

I am having trouble finding the logic that would received POSTs pushed from Instagram from the active subscriptions.  For example, responding to the "hub.challenge" required when listing subscriptions seems to be hard to locate in the code base (or just not there).  

What is there for dealing with subscriptions is valuable and useful but I would like to know whether I'm missing the other functionality or if this is something meant for users of Instasharp to build into their own application.
