### ISSUE TITLE
RequestToken(code) MVC5

### ISSUE THREAD

**Issue by criolo** [InstaSharp/InstaSharp#53]
RequestToken(code) always return a OAuthResponse Instance with
AccessToken = null
User = null

Can anyone help?

**Comment by fujiy** [comment]
Would you post a code that I can reproduce the error?

**Comment by Wirwing** [comment]
Happens the same here.

```
var clientId = ConfigurationManager.AppSettings.Get("instagram_client_id");
var clientSecret = ConfigurationManager.AppSettings.Get("instagram_client_secret");
var redirectUri = ConfigurationManager.AppSettings.Get("instagram_redirect_uri");

var config = new InstagramConfig(clientId, clientSecret, redirectUri);

var instance = InstaSharpConfig.Instance;
var redirectUrl = config.RedirectUri + "?userToken=" + user.UserRequestToken;

var link = OAuth.AuthLink(config.OAuthUri + "/authorize",
                config.ClientId, redirectUrl, scopes, OAuth.ResponseType.Code);
```


On CallBack Controller action:

```
var auth = new InstaSharp.OAuth(config);
var oauthResponse = await auth.RequestToken(code);
```

oauthResponse is always null.

**Comment by savproga** [comment]
+

**Comment by Tris10w** [comment]
@Wirwing if you remove the '/' in  "/authorize", the code provided in the example will run. I also ran into that.

 var link = OAuth.AuthLink(config.OAuthUri + "authorize", config.ClientId, config.RedirectUri, scopes, OAuth.ResponseType.Code);

**Comment by DigiBee** [comment]
The issue is actually instagram redirect uri is case sensitive. So the uri in your code should match case with the one you registered.

**Comment by fujiy** [comment]
https://github.com/InstaSharp/InstaSharp/commit/60ef02f7ff832f84620b53684b8e8d3de85a29ef
