### ISSUE TITLE
Conversion from DateTime to UnixTimestamp in UTC

### ISSUE THREAD

**Issue by minimih** [InstaSharp/InstaSharp#54]
In "Extensions/Int64Extensions.cs" the UnixTimestamp is converted to DateTime with UTC as DateTimeKind, which is correct.

However should the conversion back from DateTime to UnixTimestamp in "Extensions/DateTimeExtensions.cs" not also be in UTC? At the moment it's Converted to LocalTime.

**Comment by fujiy** [comment]
Fixed in #56
