### ISSUE TITLE
Followers>

### ISSUE THREAD

**Issue by NicoTravassos** [InstaSharp/InstaSharp#55]
Hi there is it possible to use this library to check who you following and who is not following you back?

If its possible can you maybe provide me with a example.

**Comment by fujiy** [comment]
Yes, you need to check who you is following, then do the same for each person you are following.

You will use the Relationships class

**Comment by momenimohammad23** [comment]
@fujiy 
Hi , please help me . 
is it possible see another user following and follower list in this api ?
How i can use it ?
