### ISSUE TITLE
view authenticated users followers when is private

### ISSUE THREAD

**Issue by dubmartin** [InstaSharp/InstaSharp#63]
I have authenticated my account (which is private), but when I try and get my followers, I get 0 results and a message: not allowed on this resource.

Is it possible to get my list of followers? I know other users cannot not, but as I am the authenticated user, I would have thought I could. Is there a different method to use?

**Comment by momenimohammad23** [comment]
did you do it ?

**Comment by fujiy** [comment]
It looks like a Instagram restriction
