### ISSUE TITLE
Erro in open project

### ISSUE THREAD

**Issue by hanigamini** [InstaSharp/InstaSharp#69]
Hi,
when i want open project i see this error , i am using vs 2013
---------------------------
Microsoft Visual Studio
---------------------------
The project file 'InstaSharp' cannot be opened.

The project is targeting frameworks that are either not installed or are included as part of future updates to Visual Studio. See http://go.microsoft.com/fwlink/?LinkID=287985 for more information.
---------------------------
OK   
---------------------------

**Comment by fujiy** [comment]
Do you have the latest update? http://www.microsoft.com/en-us/download/details.aspx?id=48129

**Comment by hanigamini** [comment]
Thank you , i install update 5 , but when run i have this error :
---------------------------
Microsoft Visual Studio
---------------------------
A project with an Output Type of Class Library cannot be started directly.

In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project.
---------------------------
OK   
---------------------------

**Comment by theShiva** [comment]
@hanigamini That is not a code error. Do you google much? 

You cannot run a class library project. You should add the InstaSharp project in your MVC or Web Project as a Project reference, and set that project as the startup project. See here => http://stackoverflow.com/a/5095677/325521

@fujiy I think you can close this issue out.

**Comment by hanigamini** [comment]
Hi theShiva ,
Thanks for your response , 
I know it , but InstaSharp project have this error :
![1](https://cloud.githubusercontent.com/assets/12791970/9698638/436c3e16-53d5-11e5-9beb-096239898ce6.jpg)

and this is my vs

![2](https://cloud.githubusercontent.com/assets/12791970/9698639/4b85a678-53d5-11e5-9f35-62e9ddb28e6d.jpg)

**Comment by hanigamini** [comment]
my vs about
![pic2](https://cloud.githubusercontent.com/assets/12791970/9698658/fff4d7e6-53d5-11e5-86f7-29ca17bcf858.jpg)

**Comment by fujiy** [comment]
@hanigamini you are able to create Portable Class Libraries?

**Comment by hanigamini** [comment]
Hi,
no , error in create  Portable Class Libraries project  :
---------------------------
Microsoft Visual Studio
---------------------------
An internal error occurred. Please contact Microsoft Product Support Services.
---------------------------
OK   
---------------------------

**Comment by fujiy** [comment]
So the problem seems to be at Visual Studio
