### ISSUE TITLE
The Getting Started Documentation is outdated and has several error and typos.

### ISSUE THREAD

**Issue by theShiva** [InstaSharp/InstaSharp#70]
The [Getting Started](https://github.com/InstaSharp/InstaSharp#getting-started) Documentation is outdated and has several error and typos

For example, take the following line in the [Authenticate](https://github.com/InstaSharp/InstaSharp#authenticate) section.

`var link = OAuth.AuthLink(config.OAuthURI + "/authorize", config.ClientId, config.RedirectURI, scopes, OAuth.ResponseType.Code);`

There are several issues here.
1. `OAuthURI` should be `OAuthUri`
2. `RedirectURI` should be `RedirectUri`
3. `"/authorize"` should be `"authorize"`

No.3 is the most problematic and confusing :confounded: , because it takes a trained :eyes:  [to see](http://stackoverflow.com/a/32110777/325521) the extra `/` that causes a `404 Page not Found` [error during the authentication attempt](http://stackoverflow.com/q/32074613/325521). 

There are also other issues in the sample code for the instagram callback i.e. in this one `public async Task<ActionResult> Index(string code)`

These issues are popping up for every new person who is trying to use our library, and as such, would be Instasharp users are giving up on using this library.

So it behooves us to fix this, so more people start using this beautiful and fast instagram client :stuck_out_tongue_winking_eye:

**Comment by momenimohammad23** [comment]
Can you help me ? 
after i get the access token I cant use it ! there is no document ! how i can use it ?

**Comment by fujiy** [comment]
https://github.com/InstaSharp/InstaSharp/commit/7bbf6695458e52383bb0bdda815b493e69496358
