### ISSUE TITLE
Integer overflow in Id

### ISSUE THREAD

**Issue by mtinnes** [InstaSharp/InstaSharp#71]
Looks like Instagram is returning Id's which are overflowing 32bit int defined in the InstaSharp models:

Could not convert string to integer: 2148597516. Path 'data[0].likes.data[0].id', line 1, position 2809.

**Comment by larrynburris** [comment]
I am seeing the same issue. It looks like that path leads to the UserInfo Id field.

**Comment by Shendor** [comment]
+1

**Comment by fujiy** [comment]
Working on it

**Comment by fujiy** [comment]
Fixed in 346ab37e13cb63d161e345da7e8e231dcdc80c6f and 4461aa165522a6c67db69da9cff69e4df3124a38
