### ISSUE TITLE
How to use it after Get the oauth from instagram ?

### ISSUE THREAD

**Issue by momenimohammad23** [InstaSharp/InstaSharp#75]
Hi 
please any one help me ! 
I get the code 
But now i cant use it to get user inforamation . also i see the MVC sample ..

here is my Errors :
Severity	Code	Description	Project	File	Line
/////Error on Line : 
var feed = next_max_id == null ? await _users.Feed() : await _users.Feed(next_max_id);
There is no argument given that corresponds to the required formal parameter 'minId' of 'Users.Feed(string, string, int?

and 
The name 'result' does not exist in the current context
and many Errors like this 

this is my class

public class UsersController : Controller
    {
        readonly InstaSharp.Endpoints.Users _users;

        public UsersController()
        {
            _users = new InstaSharp.Endpoints.Users(InstaSharpConfig.Instance.config, InstaSharpConfig.Instance.oauthResponse);
            
        }

        [GET("api/users/feed")]
        public async Task<ActionResult>  Feed(string next_max_id)
        {
            var feed = next_max_id == null ? await _users.Feed() : await _users.Feed(next_max_id);

            // return plain JSON
            return Json(result.Data);
        }

        [GET("api/users/{id}")]
        public ContentResult UserInfo(string id)
        {
            var user = string.IsNullOrEmpty(id) ? _users.Get() : _users.Get(id);

            return new ContentResult { Content = user.Content, ContentType = "application/json" };

        }

        //[GET("api/self/feed")]
        //public ContentResult Feed(string next_max_id)
        //{
            

        //    var feed = next_max_id == null ? _users.Feed() : _users.Feed(next_max_id);

        //    return new ContentResult { Content = feed.Content, ContentType = "application/json" };
        //}
        [GET("api/self/recent")]
        public ContentResult RecentSelf(string next_max_id)
        {

            var recent = next_max_id == null ? _users.RecentSelf() : _users.RecentSelf(next_max_id);

            return new ContentResult { Content = recent.Content, ContentType = "application/json" };
        }

        [GET("api/users/{id}/recent")]
        public ContentResult Recent(string id)
        {

            var recent = _users.Recent(id);

            return new ContentResult { Content = recent.Content, ContentType = "application/json" };

        }
    }

**Comment by momenimohammad23** [comment]
help me plz 
http://stackoverflow.com/questions/32579274/instasharp-oauthresponse-not-work

**Comment by fujiy** [comment]
You can see a example of Users.Feed at https://github.com/InstaSharp/InstaSharp/blob/master/src/InstaSharp.Tests/Users.cs#L57
