### ISSUE TITLE
Can i get another people follower and following list ?

### ISSUE THREAD

**Issue by momenimohammad23** [InstaSharp/InstaSharp#76]
Hi 
Can i get another people follower and following list ? 
for example Can i get the list of instagram user id follower ? 
or just i access to my follower and following ?

**Comment by fujiy** [comment]
Use the FollowedBy method

**Comment by momenimohammad23** [comment]
@fujiy but it just get 50 results ! and just get followers not following !

**Comment by fujiy** [comment]
To get users who you are following you call Follows. 

To get all users, you should call FollowedBy(long userId, string cursor), using cursor to get next pages, or FollowedByAll

**Comment by momenimohammad23** [comment]
@fujiy  thanks
