### ISSUE TITLE
unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll

### ISSUE THREAD

**Issue by misterraj7** [InstaSharp/InstaSharp#78]
I am trying to extract popular media pics/videos.

this is my code:

       class Program
        {
        private const string CliendID = "157c0c51ef58435893a50e0430b5f53b";
        private const string ClientSecret = "2dfa1927bde5477b952258e659b04a89";
        private const string redirectURI = "http://www.hashgurus.com/redirect.aspx";
        private static InstagramConfig config;
        private static  OAuth  Auth;
        static void  Main(string[] args)
        {
             config = new InstagramConfig(CliendID, ClientSecret,redirectURI);
            
              Auth = new OAuth(config);
              var scopes = new List<OAuth.Scope>();
              scopes.Add(OAuth.Scope.Likes);
              scopes.Add(OAuth.Scope.Basic);
              scopes.Add(OAuth.Scope.Comments);
              scopes.Add(OAuth.Scope.Relationships);

              var link = OAuth.AuthLink(config, scopes, OAuth.ResponseType.Code);

              HttpWebRequest myReq = (HttpWebRequest)WebRequest.Create(link);
              WebResponse webresponse =  myReq.GetResponse();
            
              call().Wait();
             

        }

        public static async Task call()
        {
            var authInfo = new OAuth(config);
            string code = "";
            var response = await authInfo.RequestToken(code);
            

             InstaSharp.Endpoints.Media media = new InstaSharp.Endpoints.Media(config, response);
            var result = await media.Popular();
           
        }

    }

when this line of code gets executed:
 InstaSharp.Endpoints.Media media = new InstaSharp.Endpoints.Media(config, response);

 I am getting An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll

can some one help me?

**Comment by momenimohammad23** [comment]
Hi
did you solve you problem ?
if Not , I Can send you a sample

**Comment by misterraj7** [comment]
Nope. I still get the error. How did you solve the problem,??

thanks
venkat.

**Comment by momenimohammad23** [comment]
give me your Email , I send you my sample

**Comment by misterraj7** [comment]
my email id is misterraj at the rate gmail.com

**Comment by fujiy** [comment]
AggregateException is being thew because you called Wait(). We need the original exception. You can catch it using a try {}catch(Exception ex){ex.GetBaseException()}
