### ISSUE TITLE
Error converting value \"followed_by\" to type 'InstaSharp.Models.IncomingStatus

### ISSUE THREAD

**Issue by maxenz** [InstaSharp/InstaSharp#82]
Im trying to get the relationship between my authenticated user, and another user.

When i make this call:

`var relationships = new InstaSharp.Endpoints.Relationships(config, apiResponse);
var relationshipResponse = relationships.Relationship(Convert.ToInt32(userId)).GetAwaiter().GetResult();`

When i debug it, at the moment the JsonConverter tries to convert it from json to a RelationResponse Object it crashes.

Thanks

**Comment by fujiy** [comment]
Can't reproduce

**Comment by momenimohammad23** [comment]
@fujiy  @maxenz  
Hi , I have this problem too
`Exception	Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in mscorlib.dll ("Error converting value "followed_by" to type 'InstaSharp.Models.IncomingStatus'. Path 'data.incoming_status', line 1, position 116.")	11.47s		[12984]
`
