### ISSUE TITLE
how i can get all comments and likes detail on a Media ?

### ISSUE THREAD

**Issue by momenimohammad23** [InstaSharp/InstaSharp#84]
Hi i use this code for get comments and likes : 
                var co = await comments.Get(post.Id);
                var li = await likes.Get(post.Id);
 but no fixed count of likes and comments !!! some times get 148 comment from 159 , 107 like from 1788 like !! whay ?!?
is there any way for get all ??
if no , whay not fixed likes amount ?
thanks from @fujiy

**Comment by fujiy** [comment]
It's a Instagram's limitation
