### ISSUE TITLE
OAuth without async

### ISSUE THREAD

**Issue by empiteisuru** [InstaSharp/InstaSharp#87]
I moved following code to business layer. and remove async part.
Then I cant access to Users. Cant we do this without async

var oAuthResponse = Session["InstaSharp.AuthInfo"] as OAuthResponse;
    if (oAuthResponse == null)
    {
        return RedirectToAction("Login");
    }
    var users = new Endpoints.Users(config, oAuthResponse);
    var feed = await users.Feed(null, null, null);

**Comment by fujiy** [comment]
Any reason to not use async in business layer
