### ISSUE TITLE
Integer overflow in AuthorId 

### ISSUE THREAD

**Issue by kopenk** [InstaSharp/InstaSharp#88]
In class OEmbedResponse, i get error JSON int overflow...

public class OEmbedResponse
    {
        public OEmbedResponse();

        [JsonProperty("author_id")]
        public int AuthorId { get; set; }

its the same as userId... should change it to long

**Comment by meggermann** [comment]
same problem ..

**Comment by fujiy** [comment]
Could you provide a repro, please?
