### ISSUE TITLE
Update API

### ISSUE THREAD

**Issue by momenimohammad23** [InstaSharp/InstaSharp#93]
Hi
Instagram Update something that say in this page : 
https://www.instagram.com/developer/sandbox/
and new api developer users Cannot use it !
please Update Then API something change such as login permissions : 
https://www.instagram.com/developer/authorization/
Thanks from @fujiy

**Comment by Dan9boi** [comment]
+1 I would like the API updated to the latest, as well :-)

**Comment by momenimohammad23** [comment]
@Dan9boi  hi 
its update but i cant get any data from instagram with new version of instagram api id 
Can you help me?

**Comment by Telaran** [comment]
> its update but i cant get any data from instagram with new version of instagram api id 

The question would be: What do you mean by "can't get any".

`internal static CustomInstaSharpConfiguartion InstagramConfig = new CustomInstaSharpConfiguartion()`
`        {`
`            ClientId = "aclientid",`
`            ClientSecret = "aclientsecret",`
`            RedirectUri = "anUrlWhichisConfiguredOnInstagram"`
`        };`
`var auth = new OAuth(InstagramConfig);`
`var oauthResponse = await auth.RequestToken(code);`
`if (oauthResponse == null || oauthResponse.AccessToken == null) return null;`
`var user = new InstaSharp.Endpoints.Users(instagramConfig, oauthResponse);`
`var self = await user.GetSelf();`
`var id = self.Data.Id.ToString()`

Maybe you have to check again the Endpoints and Scopes?

**Comment by fujiy** [comment]
Instagram just made hard to be a API/App developer, like Twitter has made some time ago.
I couldn't get a Client-Id approved to leave the sandbox, so I can't test the API

**Comment by fujiy** [comment]
Done
