### ISSUE TITLE
Message = "Method not found: 'Void System.Net.Http.HttpClientHandler.set_AutomaticDecompression(System.Net.DecompressionMethods)'."

### ISSUE THREAD

**Issue by buffalo0** [InstaSharp/InstaSharp#94]
This might be and issue with my set up but this code

` public static async Task<string> GetUserRecentMedia(string userId)
        {
            string response = string.Empty;
            try
            {
                InstagramConfig config = new InstagramConfig("83ef77ea76784872a8cda14cc677deb4", "654530e2986a43bd8c02a4fedb1a0de3");
                Users usersEndpoints = new Users(config, null);
                response = JsonConvert.SerializeObject(await usersEndpoints.Recent(userId));
            }
            catch (Exception ex) { }
            return response;
        }`

Gives me this error message "Method not found: 'Void System.Net.Http.HttpClientHandler.set_AutomaticDecompression(System.Net.DecompressionMethods)'." when it gets to  `Users usersEndpoints = new Users(config, null);`

Anybody come across this before?

Cheers

**Comment by momenimohammad23** [comment]
Hi
are you in sand box mode ?
Can you get your profile info ? such as your name , username , ...

**Comment by fujiy** [comment]
Could you paste your packages.config content?
