### ISSUE TITLE
Error converting value "followed_by" to type 'InstaSharp.Models.IncomingStatus'. Path 'data.incoming_status', line 1, position 116.

### ISSUE THREAD

**Issue by momenimohammad23** [InstaSharp/InstaSharp#95]
I use it for get relation Data , But get API Error !! i think it need to Update 

InstaSharp.Endpoints.Relationships _rel = new InstaSharp.Endpoints.Relationships(_config, _oauth);
var relation = await _rel.Relationship(long.Parse(userid.ToString()));
__________________________
Event Type	Event	Time	Duration	Thread	Detail Description
Exception	Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in mscorlib.dll ("Error converting value "followed_by" to type 'InstaSharp.Models.IncomingStatus'. Path 'data.incoming_status', line 1, position 116.")	616.45s		[8352]

**Comment by bhangu** [comment]
Getting the same thing.

**Comment by momenimohammad23** [comment]
@bhangu did you get public tken from instagram ??

**Comment by bhangu** [comment]
Yes, basically the compiled Dll is missing the Json flag on the enum

I downloaded the code and changed the enum name to followed_by and removed
the Json flag.

So it's working for me now, but it's bit of a hack.

**Comment by fujiy** [comment]
What version are you using?

**Comment by bhangu** [comment]
The latest from nuget.

2.0. Something.

**Comment by fujiy** [comment]
That version have the attribute:

    public enum IncomingStatus
    {
        [JsonProperty("followed_by")]
        FollowedBy,

**Comment by bhangu** [comment]
Yeah, I can see that in the code, but when you see the compiled Dll, it's
not there.

Please use refactor to see the Dll provided in the nuget.

You can test it out by trying to access the relationship endpoint between
two users.

Cheer,
Mandeep

**Comment by fujiy** [comment]
Fixed on #f3992fe
