### ISSUE TITLE
Issue displaying user feed

### ISSUE THREAD

**Issue by SaemiVald** [InstaSharp/InstaSharp#96]
I kept getting an error when trying to display the feed for my account.
I changed the following and now it works:

File: Users.cs

public Task<MediasResponse> Feed(string maxId, string minId, int? count)
        {
            //var request = Request("self/feed"); 
            var request = Request("self/media/recent");

**Comment by fujiy** [comment]
self/feed is deprecated, just old client-ids can access. It returned the feed of the user

self/media/recent returns your own photos. Not your feed
